SELECT NAME, COUNT(NAME) AS "COUNT"
FROM ANIMAL_INS
GROUP BY NAME
HAVING COUNT(NAME) >= 2
ORDER BY NAME

SELECT NAME, COUNT(NAME) AS COUNT
FROM ANIMAL_INS 
WHERE NOT NAME IS NULL 
GROUP BY NAME
HAVING COUNT(NAME) > 1
ORDER BY NAME