# 첫번째 방법
SELECT NAME, COUNT(*) AS COUNT 
FROM ANIMAL_INS 
GROUP BY NAME 
HAVING COUNT(NAME) >= 2 
ORDER BY NAME

# 두번째 방법
SELECT NAME, COUNT(NAME) AS COUNT 
FROM ANIMAL_INS 
WHERE NAME IS NOT NULL 
GROUP BY NAME
HAVING COUNT(NAME) >= 2 
ORDER BY NAME
