-- 보호소에서 중성화한 동물
-- INS.SEX_UPON_INTAKE 와 
-- OUTS.SEX_UPON_INTAKE 상태가 다른 동물찾기

SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME 
FROM ANIMAL_INS I JOIN ANIMAL_OUTS O 
WHERE I.ANIMAL_ID = O.ANIMAL_ID AND I.SEX_UPON_INTAKE != O.SEX_UPON_OUTCOME
ORDER BY I.ANIMAL_ID