-- 이름없는 동물의 아이디
SELECT ANIMAL_ID FROM ANIMAL_INS 
WHERE NAME IS NULL;

-- 이름있는 동물의 아이디
SELECT ANIMAL_ID FROM ANIMAL_INS
WHERE NAME IS NOT NULL; 

-- NULL 처리
SELECT ANIMAL_TYPE, IFNULL(NAME,'No name')  
    -- 만약 NAME이 NULL이면 No name으로 표시
AS NAME, SEX_UPON_INTAKE 
FROM ANIMAL_INS 
ORDER BY ANIMAL_ID;