-- 최댓값 구하기
SELECT DATETIME 
FROM ANIMAL_INS 
ORDER BY DATETIME DESC 
LIMIT 1;

-- 최솟값 구하기
SELECT DATETIME 
FROM ANIMAL_INS 
ORDER BY DATETIME 
LIMIT 1;

-- 동물수 구하기
SELECT COUNT(*) FROM ANIMAL_INS;

-- 중복 제거하기
SELECT COUNT(DISTINCT NAME) 
FROM ANIMAL_INS 
WHERE NAME IS NOT NULL;