# 주문량이 많은 아이스크림들 조회하기
SELECT JU.FLAVOR
FROM JULY JU, FIRST_HALF FI
WHERE JU.FLAVOR = FI.FLAVOR
GROUP BY JU.FLAVOR
ORDER BY SUM(JU.TOTAL_ORDER) + SUM(FI.TOTAL_ORDER) DESC
LIMIT 3


SELECT A.FLAVOR
FROM FIRST_HALF A 
LEFT JOIN JULY B ON B.FLAVOR = A.FLAVOR
GROUP BY A.FLAVOR
ORDER BY SUM(A.TOTAL_ORDER) + SUM(B.TOTAL_ORDER) DESC
LIMIT 3

SELECT FLAVOR
FROM (
    SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF
    UNION
    SELECT FLAVOR, TOTAL_ORDER FROM JULY
) A
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3