# 취소되지 않은 진료 예약 조회하기
SELECT AP.APNT_NO, PT.PT_NAME, PT.PT_NO, DR.MCDP_CD, DR.DR_NAME, AP.APNT_YMD
FROM PATIENT PT, DOCTOR DR, APPOINTMENT AP
WHERE PT.PT_NO = AP.PT_NO AND DR.MCDP_CD = AP.MCDP_CD AND DR.DR_ID = AP.MDDR_ID
    AND AP.APNT_CNCL_YN = 'N' AND AP.MCDP_CD = 'CS'
    AND DATE_FORMAT(APNT_YMD,'%Y%m%d') = '20220413'
ORDER BY AP.APNT_YMD ASC;
--------------------------------------------
SELECT app.APNT_NO, pat.PT_NAME, app.PT_NO, app.MCDP_CD, doc.DR_NAME, app.APNT_YMD FROM APPOINTMENT AS app
    INNER JOIN PATIENT AS pat
    ON pat.PT_NO = app.PT_NO
    INNER JOIN DOCTOR AS doc 
    ON doc.DR_ID = app.MDDR_ID
WHERE app.APNT_YMD LIKE '%2022-04-13%' AND app.APNT_CNCL_YN = 'N' AND app.MCDP_CD = 'CS'
GROUP BY app.APNT_YMD
ORDER BY app.APNT_YMD ASC;
--------------------------------------------
SELECT a.APNT_NO, p.PT_NAME,p.PT_NO, a.MCDP_CD, d.DR_NAME,a.APNT_YMD
FROM APPOINTMENT a
LEFT JOIN PATIENT p ON a.PT_NO = p.PT_NO
LEFT JOIN DOCTOR d ON a.MDDR_ID = d.DR_ID
WHERE DATE_FORMAT(a.APNT_YMD,'%Y-%m-%d') = '2022-04-13' AND a.MCDP_CD = 'CS' AND a.APNT_CNCL_YN = 'N'
ORDER BY a.APNT_YMD ASC