#1 중성화 여부 파악하기
SELECT ANIMAL_ID, NAME, IF ((SEX_UPON_INTAKE LIKE 'Neutered%') OR (SEX_UPON_INTAKE LIKE 'Spayed%'), "O", "X") AS "중성화"
FROM ANIMAL_INS
ORDER BY ANIMAL_ID

#2 오랜 기간 보호한 동물(2)
SELECT I.ANIMAL_ID, I.NAME 
FROM ANIMAL_INS I 
JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID 
ORDER BY O.DATETIME-I.DATETIME DESC 
LIMIT 2

#3 DATETIME에서 DATE로 형 변환
SELECT ANIMAL_ID, NAME, DATE_FORMAT(DATETIME,'%Y-%m-%d')
FROM ANIMAL_INS
ORDER BY ANIMAL_ID