# 상품을 구매한 회원 비율 구하기
SELECT YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT u.USER_ID) AS PUCHASED_USERS,
    ROUND(COUNT(DISTINCT u.USER_ID) / COUNT, 1) AS PUCHASED_RATIO
FROM ONLINE_SALE o
    INNER JOIN (
        SELECT USER_ID,
            COUNT(*) OVER() AS COUNT
        FROM USER_INFO
        WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31'
    ) u ON u.USER_ID = o.USER_ID
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH
---------------------------------------------------------------------
SELECT DISTINCT YEAR
    , MONTH
    , PUCHASED_USERS AS PUCHASED_USERS
    , ROUND((PUCHASED_USERS / JOINED_USER_CNT), 1) AS PUCHASED_RATIO
FROM(
    SELECT B.YEAR
        , B.MONTH
        , COUNT(B.USER_ID) OVER(PARTITION BY B.YEAR, B.MONTH) AS PUCHASED_USERS
        , A.JOINED_USER_CNT
    FROM(
        SELECT USER_ID, JOINED_USER_CNT
        FROM USER_INFO MT1
        JOIN (
            SELECT COUNT(*) AS JOINED_USER_CNT
            FROM USER_INFO
            WHERE YEAR(JOINED) = '2021'
            )X
            ON TRUE
        WHERE YEAR(JOINED) = '2021'
        )A
    INNER JOIN(
        SELECT USER_ID 
            , YEAR(SALES_DATE) AS YEAR
            , MONTH(SALES_DATE) AS MONTH
        FROM ONLINE_SALE
        GROUP BY USER_ID, YEAR(SALES_DATE), MONTH(SALES_DATE)
        )B
        ON A.USER_ID = B.USER_ID
    )C
ORDER BY YEAR ASC, MONTH ASC;
---------------------------------------------------------------------
SELECT TO_CHAR(S.SALES_DATE, 'YYYY') YEAR
     , TO_NUMBER(TO_CHAR(S.SALES_DATE, 'FMMM')) MONTH
     , COUNT(DISTINCT S.USER_ID) PUCHASED_USERS
     , ROUND(COUNT(DISTINCT S.USER_ID) / (SELECT COUNT(*)
                                            FROM USER_INFO
                                           WHERE TO_CHAR(JOINED, 'YYYY') = '2021'), 1) PUCHASED_RATIO
  FROM USER_INFO I, ONLINE_SALE S
 WHERE I.USER_ID = S.USER_ID
   AND TO_CHAR(I.JOINED, 'YYYY') = '2021'
 GROUP BY TO_CHAR(S.SALES_DATE, 'YYYY'), TO_NUMBER(TO_CHAR(S.SALES_DATE, 'FMMM'))
 ORDER BY TO_CHAR(S.SALES_DATE, 'YYYY'), TO_NUMBER(TO_CHAR(S.SALES_DATE, 'FMMM'))