# 과일로 만든 아이스크림 고르기
SELECT FH.FLAVOR
FROM FIRST_HALF AS FH
JOIN ICECREAM_INFO AS II
USING (FLAVOR)
WHERE TOTAL_ORDER > 3000
AND INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC;

SELECT A.FLAVOR
FROM FIRST_HALF AS A
INNER JOIN ICECREAM_INFO AS B
ON A.FLAVOR=B.FLAVOR
WHERE A.TOTAL_ORDER>=3000 AND INGREDIENT_TYPE LIKE 'fruit_based'
ORDER BY A.TOTAL_ORDER DESC

SELECT A.FLAVOR FROM (SELECT * FROM FIRST_HALF WHERE TOTAL_ORDER > 3000) A, 
(SELECT * FROM ICECREAM_INFO WHERE INGREDIENT_TYPE = 'fruit_based') B WHERE A.FLAVOR = B.FLAVOR
ORDER BY A.TOTAL_ORDER DESC