#1 모든 레코드 조회하기
select ANIMAL_ID, ANIMAL_TYPE, DATETIME, INTAKE_CONDITION, NAME, SEX_UPON_INTAKE
from ANIMAL_INS
ORDER BY ANIMAL_ID

#2 역순 정렬하기
select NAME, DATETIME
from ANIMAL_INS
order by ANIMAL_ID DESC

#3 아픈 동물 찾기
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION= "SICK"
ORDER BY ANIMAL_ID