# 조건에 맞는 회원수 구하기
SELECT COUNT(*) AS USERS
FROM USER_INFO
WHERE YEAR(JOINED) = 2021 AND AGE BETWEEN 20 AND 29;

SELECT COUNT(USER_ID) AS USERS
FROM USER_INFO
WHERE LEFT(JOINED, 4) = "2021" AND AGE >= 20 AND AGE <= 29;

SELECT COUNT(AGE) 
FROM USER_INFO 
WHERE AGE BETWEEN 20 AND 29 AND DATE_FORMAT(JOINED, '%Y') = 2021