# 카테고리 별 도서 판매량 집계하기
SELECT b.CATEGORY, SUM(s.SALES) AS TOTAL_SALES 
FROM BOOK AS b
JOIN BOOK_SALES as s ON b.BOOK_ID = s.BOOK_ID
WHERE SALES_DATE LIKE '%2022-01-%'
-- where date_format(b.sales_date, '%Y-%m') = '2022-01'
-- WHERE MONTH(S.SALES_DATE) = 1
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY



SELECT B.CATEGORY, SUM(BS.SALES)
FROM BOOK AS B, BOOK_SALES AS BS
WHERE YEAR(BS.SALES_DATE) = '2022'
AND MONTH(BS.SALES_DATE) = '01'
AND BS.BOOK_ID = B.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY