SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.ANIMAL_TYPE, ANIMAL_INS.NAME 
FROM ANIMAL_INS 
JOIN ANIMAL_OUTS 
WHERE ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID AND ANIMAL_INS .SEX_UPON_INTAKE != ANIMAL_OUTS.SEX_UPON_OUTCOME   #이후에 들어올때와 나올때의 성별이 다른 동물을 찾기
ORDER BY ANIMAL_INS.ANIMAL_ID

SELECT A.ANIMAL_ID,A.ANIMAL_TYPE, A.NAME
FROM ANIMAL_INS A
JOIN ANIMAL_OUTS B
ON A.ANIMAL_ID=B.ANIMAL_ID
WHERE A.SEX_UPON_INTAKE LIKE 'INTACT%' # 성별 및 중성화 여부
AND (B.SEX_UPON_OUTCOME LIKE 'SPAYED%' # 중성화를 거친 동물
OR B.SEX_UPON_OUTCOME LIKE 'NEUTERED%') # 중성화를 거친 동물
ORDER BY A.ANIMAL_ID